PRO_APP_DES:
    appium_port: 4723
    desired_caps:
        automationName: UIAutomator2
        platformName: Android
        platformVersion: 7.1.2
        deviceName: Android Emulator
        noReset: true
        appPackage: com.ss.android.ugc.aweme
        appActivity: com.ss.android.ugc.aweme.splash.SplashActivity
TEST_APP_DES:
    appium_port: 4723
    desired_caps:
        automationName: UIAutomator2
        platformName: Android
        platformVersion: 7.1.2
        deviceName: Android Emulator
        noReset: true
        appPackage: com.cisdi.building.test
        appActivity: com.cisdi.building.activity.SplashActivity
53banxue:
    apk_info:
        pgy_url: http://www.pgyer.com/HnXQ
        apk_name_keywords:
        - 53伴学
        - 测试
        phone_address: 127.0.0.1:62001
    appium_port: 4723
    desired_caps:
        automationName: UIAutomator2
        platformName: Android
        platformVersion: 7.1.2
        deviceName: Android Emulator
        noReset: true
        appPackage: com.cisdi.building.test
        appActivity: com.cisdi.building.activity.SplashActivity
